---
ansible_ssh_common_args: >-
  {{ ansible_ssh_base_args }}
  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  -o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p {{ ansible_user }}@{{ hostvars[groups['public'][0]]['ansible_host'] | default(groups['public'][0]) }}"