[all:vars]
ansible_ssh_base_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
ansible_user=ubuntu
ansible_ssh_common_args='{{ ansible_ssh_base_args }}'

[bastion]

[private]

[private:vars]
ansible_ssh_common_args='{{ ansible_ssh_base_args }} -o ProxyJump={{ ansible_user }}@{{ hostvars[groups["bastion"][0]]["ansible_host"] | default(groups["bastion"][0]) }}'
